# @package _group_
type: winding
input_size: 5
observation_size: 2
dataset_window: 2
train_path: data/winding/winding_train.csv
val_path: data/winding/winding_val.csv
test_path: data/winding/winding_test.csv
target_names: ['tension1', 'tension2']
